version: "3.9"
services:
  docker-saigneur-candidat:
    image: saigneur-candidat
    container_name: msaigneur-candidat
    build:
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    restart: always
    depends_on:
      - docker-saigneur-postgres
      - docker-saigneur-discovery
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker-saigneur-postgres:5432/saigneurcandidatdb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: adminpostgres
    networks:
      - saigneur-network

networks:
  saigneur-network:
    external: true
